### ISSUE TITLE
Run FormReader.find() and bypass barcode scanning?

### ISSUE THREAD

**Issue by kcollignon** [creatale/node-fv#2]
Hello,
I'm having some issues running a `.find()` on an image. I am getting this error:

```
/Users/demouser/node_modules/fv/lib/find_barcodes.js:29
  clearedImage = new dv.Image(image);
                 ^
TypeError: expected (image: Image) or (image1: Image, image2: Image, image3: Image) or (format: String, image: Buffer, [width: Int32, height: Int32]) or no arguments at all
```

Would you happen to know why I am getting this error? I have verified that my image object is indeed there.

**Comment by WolfgangFellger** [comment]
Into the blue: Do you have two copies of dv installed? (see `npm list dv`) Unfortunately, the `Image`s of two compiled versions are incompatible (tips welcome on how to resolve this better).

If you use dv in your main project, it must be the *exact same version* as referenced in fv's `package.json`. To fix, you can directly delete `node_modules/fv/node_modules/dv`, so fv will pick up the version installed for your project.

**Comment by kcollignon** [comment]
@WolfgangFellger that worked! had to delete that folder that you referenced. Thank you so much!!!!
